# Generated by Django 4.2.7 on 2025-10-02 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skillora_app', '0003_student_liked_courses_student_saved_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('internship_type', models.CharField(choices=[('internship', 'Internship'), ('industrial_training', 'Industrial Training'), ('placement', 'Full-time Placement')], default='internship', max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('required_skills', models.TextField(help_text='Comma-separated skills')),
                ('department_preference', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('duration_months', models.IntegerField(help_text='Duration in months')),
                ('stipend_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stipend_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seats_available', models.IntegerField(default=1)),
                ('seats_filled', models.IntegerField(default=0)),
                ('application_deadline', models.DateTimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('has_placement_potential', models.BooleanField(default=False)),
                ('placement_conversion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage', max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships_posted', to='skillora_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('mentor_approval_pending', 'Mentor Approval Pending'), ('mentor_approved', 'Mentor Approved'), ('mentor_rejected', 'Mentor Rejected'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=30)),
                ('cover_letter', models.TextField()),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='applications/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor_approval_date', models.DateTimeField(blank=True, null=True)),
                ('mentor_comments', models.TextField(blank=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_location', models.CharField(blank=True, max_length=200)),
                ('interview_notes', models.TextField(blank=True)),
                ('selection_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='skillora_app.internship')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='liked_courses',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('company', 'Company'), ('placement_cell', 'Placement Cell'), ('mentor', 'Mentor')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('skills', models.TextField(help_text='Comma-separated skills')),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('department', models.CharField(max_length=100)),
                ('year_of_study', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')])),
                ('graduation_year', models.IntegerField()),
                ('preferred_locations', models.TextField(help_text='Comma-separated preferred locations')),
                ('preferred_industries', models.TextField(help_text='Comma-separated preferred industries')),
                ('internship_preferences', models.CharField(choices=[('internship', 'Internship'), ('industrial_training', 'Industrial Training'), ('placement', 'Full-time Placement')], default='internship', max_length=20)),
                ('is_placement_ready', models.BooleanField(default=False)),
                ('placement_preference_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_profile', to='skillora_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Directorate of Technical Education', max_length=100)),
                ('organization', models.CharField(default='Government of Rajasthan', max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('office_location', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application_status', 'Application Status Update'), ('interview_scheduled', 'Interview Scheduled'), ('deadline_reminder', 'Deadline Reminder'), ('mentor_approval', 'Mentor Approval Required'), ('new_opportunity', 'New Opportunity'), ('feedback_request', 'Feedback Request'), ('certificate_ready', 'Certificate Ready')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skillora_app.internshipapplication')),
                ('related_internship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skillora_app.internship')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField(default=0)),
                ('max_mentees', models.IntegerField(default=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(max_length=100)),
                ('supervisor_email', models.EmailField(max_length=254)),
                ('supervisor_designation', models.CharField(max_length=100)),
                ('technical_skills_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('communication_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('teamwork_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('punctuality_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('overall_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('strengths', models.TextField()),
                ('areas_for_improvement', models.TextField()),
                ('additional_comments', models.TextField(blank=True)),
                ('completion_date', models.DateField()),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('recommend_for_placement', models.BooleanField(default=False)),
                ('placement_recommendation_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='skillora_app.internshipapplication')),
            ],
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillora_app.mentor'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_applications', to='skillora_app.student'),
        ),
        migrations.AddField(
            model_name='internship',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skillora_app.placementcell'),
        ),
        migrations.AlterUniqueTogether(
            name='internshipapplication',
            unique_together={('student', 'internship')},
        ),
    ]
