# Generated by Django 5.2.5 on 2025-10-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillora_app', '0005_assignment_coursematerial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='ai_verifications/')),
                ('verification_type', models.CharField(choices=[('offer_letter', 'Offer Letter'), ('resume', 'Resume'), ('certificate', 'Certificate'), ('document', 'Document')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('verification_result', models.TextField(blank=True)),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_verifications', to='skillora_app.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_uploads/')),
                ('upload_type', models.CharField(choices=[('student_data', 'Student Data'), ('placement_records', 'Placement Records'), ('company_data', 'Company Data'), ('job_postings', 'Job Postings')], max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('processed_records', models.IntegerField(default=0)),
                ('total_records', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_uploads', to='skillora_app.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('placement_summary', 'Placement Summary'), ('student_analytics', 'Student Analytics'), ('company_performance', 'Company Performance'), ('recruitment_trends', 'Recruitment Trends'), ('excel_analysis', 'Excel Data Analysis')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='reports/')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='skillora_app.company')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
