# Generated by Django 5.2.5 on 2025-10-25 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillora_app', '0006_aiverification_excelupload_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='placementcell',
            name='user',
        ),
        migrations.AlterField(
            model_name='internship',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_internships', to='skillora_app.company'),
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='mentor_approval_date',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='mentor_comments',
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('company', 'Company')], default='student', max_length=20),
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='PlacementCell',
        ),
    ]
