# Generated by Django 5.2.5 on 2025-10-25 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillora_app', '0007_remove_internshipapplication_mentor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('total_offers', models.IntegerField(default=0)),
                ('placement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('placed_students', models.IntegerField(default=0)),
                ('not_placed', models.IntegerField(default=0)),
                ('higher_studies', models.IntegerField(default=0)),
                ('entrepreneurs', models.IntegerField(default=0)),
                ('family_business', models.IntegerField(default=0)),
                ('competitive_exam', models.IntegerField(default=0)),
                ('highest_package', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('average_package', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_stipend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iqac_approved', models.IntegerField(default=0)),
                ('iqac_pending', models.IntegerField(default=0)),
                ('iqac_rejected', models.IntegerField(default=0)),
                ('partner_companies', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats', to='skillora_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('total_students', models.IntegerField(default=0)),
                ('placed_students', models.IntegerField(default=0)),
                ('placement_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('batch_year', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_stats', to='skillora_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('package_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stipend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('placement_date', models.DateField()),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('iqac_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_records', to='skillora_app.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_records', to='skillora_app.student')),
            ],
        ),
    ]
