# Generated by Django 5.2.5 on 2025-10-27 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillora_app', '0009_studentprofile_phone_alter_studentprofile_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom, Google Meet, or other meeting link')),
                ('meeting_password', models.CharField(blank=True, max_length=100)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_pattern', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='skillora_app.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='skillora_app.teacher')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
