# Generated by Django 5.2.5 on 2025-11-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillora_app', '0014_courselesson_coursetask_courseprogress_savedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='additional_info',
            field=models.TextField(blank=True, default='', help_text='Any additional details about the course'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(default=True, help_text='Certificate provided on completion'),
        ),
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.CharField(default='Life Time', help_text='e.g., Life Time, 30 days, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='learners_count',
            field=models.IntegerField(default=0, help_text='Number of learners enrolled'),
        ),
        migrations.AddField(
            model_name='course',
            name='lectures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Course rating out of 5.0', max_digits=3),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of skills (e.g., HTML, CSS, JavaScript)'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, default='', help_text='Course syllabus topics (one per line or JSON format)'),
        ),
    ]
